import os
from datetime import datetime
from tkinter import filedialog

DARK_BLUE = "1F3864"
WHITE = "FFFFFF"
BLACK = "000000"
LIGHT_GRAY = "F2F2F2"


def _set_cell_background(cell, color_hex):
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    shading_elm = OxmlElement("w:shd")
    shading_elm.set(qn("w:fill"), color_hex)
    cell._tc.get_or_add_tcPr().append(shading_elm)


def _set_cell_text(cell, text, bold=False, color_hex=BLACK, size=10, align=None):
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    cell.text = ""
    p = cell.paragraphs[0]
    if align == "center":
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(text)
    run.bold = bold
    run.font.size = Pt(size)
    run.font.color.rgb = RGBColor.from_string(color_hex)


class WordExporter:
  """Utility engine to export report data into formatted MS Word (.docx) documents."""

  @staticmethod
  def export_report_to_word(report_data: dict, default_filename: str = "library_report.docx"):
    try:
      file_path = filedialog.asksaveasfilename(
          defaultextension=".docx",
          filetypes=[("Word Documents", "*.docx"), ("All Files", "*.*")],
          initialfile=f"{report_data.get('period', 'System')}_Report.docx",
          title="Export Report to MS Word",
      )
      if not file_path:
        return {"success": False, "message": "Export cancelled by user."}

      try:
        import docx
      except ImportError:
        txt_path = file_path.replace(".docx", ".txt")
        with open(txt_path, "w", encoding="utf-8") as f:
          f.write(f"SMART LIBRARY SYSTEM - {report_data.get('period', '').upper()} REPORT\n")
          f.write("=" * 55 + "\n\n")
          f.write(f"Total Check-Ins: {report_data.get('total_checkins', 0)}\n")
          f.write(f"Total Check-Outs: {report_data.get('total_checkouts', 0)}\n")
          f.write(f"Estimated Fine Collection: Rs. {report_data.get('estimated_fine_collection', 0)}\n")
        return {"success": True, "message": f"python-docx not installed — exported as plain text '{os.path.basename(txt_path)}' instead."}

      from docx import Document
      from docx.shared import Pt, RGBColor
      from docx.enum.text import WD_ALIGN_PARAGRAPH

      doc = Document()

      # ---- Branding header ----
      header_p = doc.add_paragraph()
      header_run = header_p.add_run("📘  Smart Library System")
      header_run.bold = True
      header_run.font.size = Pt(14)
      header_run.font.color.rgb = RGBColor.from_string(DARK_BLUE)

      # ---- Title ----
      title_p = doc.add_paragraph()
      title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
      title_run = title_p.add_run(f"{report_data.get('period', 'Daily')} Activity Report")
      title_run.bold = True
      title_run.font.size = Pt(20)
      title_run.font.color.rgb = RGBColor.from_string(DARK_BLUE)

      doc.add_paragraph()

      # ---- Metadata table ----
      meta_table = doc.add_table(rows=3, cols=2)
      meta_table.style = "Table Grid"
      meta_rows = [
          ("Report Type", f"{report_data.get('period', 'Daily')} Report"),
          ("Generated On", datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
          ("Generated By", report_data.get("generated_by", "System")),
      ]
      for i, (label, value) in enumerate(meta_rows):
        _set_cell_text(meta_table.rows[i].cells[0], label, bold=True, color_hex=WHITE)
        _set_cell_background(meta_table.rows[i].cells[0], DARK_BLUE)
        _set_cell_text(meta_table.rows[i].cells[1], str(value), color_hex=BLACK)
        _set_cell_background(meta_table.rows[i].cells[1], LIGHT_GRAY)

      doc.add_paragraph()

      def add_section(title_text, build_content_fn):
        """Adds a dark-blue header bar (white bold text) followed by a bordered content box."""
        header_table = doc.add_table(rows=1, cols=1)
        _set_cell_text(header_table.rows[0].cells[0], title_text, bold=True, color_hex=WHITE, size=12)
        _set_cell_background(header_table.rows[0].cells[0], DARK_BLUE)

        content_table = doc.add_table(rows=1, cols=1)
        content_table.style = "Table Grid"
        build_content_fn(content_table.rows[0].cells[0])
        doc.add_paragraph()

      # ---- Attendance Summary ----
      def _attendance_content(cell):
        cell.text = ""
        p1 = cell.paragraphs[0]
        r1 = p1.add_run(f"Total Check-Ins: {report_data.get('total_checkins', 0)}")
        r1.font.color.rgb = RGBColor.from_string(BLACK)
        r1.font.size = Pt(10)
        p2 = cell.add_paragraph()
        r2 = p2.add_run(f"Total Check-Outs: {report_data.get('total_checkouts', 0)}")
        r2.font.color.rgb = RGBColor.from_string(BLACK)
        r2.font.size = Pt(10)

      add_section("Attendance Summary", _attendance_content)

      # ---- Department-Wise Book Issuance ----
      def _dept_content(cell):
        dept_issues = report_data.get("department_issues", [])
        cell.text = ""
        if not dept_issues:
          p = cell.paragraphs[0]
          r = p.add_run("No department issuance data for this period.")
          r.font.color.rgb = RGBColor.from_string(BLACK)
          r.font.size = Pt(10)
          return
        for idx, d in enumerate(dept_issues):
          p = cell.add_paragraph() if idx > 0 else cell.paragraphs[0]
          r = p.add_run(f"{d.get('department', 'Unknown')}: {d.get('count', 0)} books issued")
          r.font.color.rgb = RGBColor.from_string(BLACK)
          r.font.size = Pt(10)

      add_section("Department-Wise Book Issuance", _dept_content)

      # ---- Most Issued Books ----
      def _most_issued_content(cell):
        books = report_data.get("most_issued_books", [])
        cell.text = ""
        if not books:
          p = cell.paragraphs[0]
          r = p.add_run("No book issuance recorded for this period.")
          r.font.color.rgb = RGBColor.from_string(BLACK)
          r.font.size = Pt(10)
          return
        for idx, b in enumerate(books):
          p = cell.add_paragraph() if idx > 0 else cell.paragraphs[0]
          r = p.add_run(f"{idx + 1}. {b.get('title', 'N/A')} — issued {b.get('issue_count', 0)} times")
          r.font.color.rgb = RGBColor.from_string(BLACK)
          r.font.size = Pt(10)

      add_section("Most Issued Books", _most_issued_content)

      # ---- Overdue / Unreturned Books ----
      def _unreturned_content(cell):
        unreturned = report_data.get("unreturned_students", [])
        cell.text = ""
        if not unreturned:
          p = cell.paragraphs[0]
          r = p.add_run("No overdue books at this time.")
          r.font.color.rgb = RGBColor.from_string(BLACK)
          r.font.size = Pt(10)
          return
        for idx, s in enumerate(unreturned):
          p = cell.add_paragraph() if idx > 0 else cell.paragraphs[0]
          r = p.add_run(
              f"{s.get('student_name', 'N/A')} ({s.get('student_id', '')}, {s.get('department', '')}) "
              f"— due {s.get('expected_return_date_time', 'N/A')}"
          )
          r.font.color.rgb = RGBColor.from_string(BLACK)
          r.font.size = Pt(10)

      add_section("Overdue / Unreturned Books", _unreturned_content)

      # ---- Fine Collection Estimate ----
      def _fine_content(cell):
        cell.text = ""
        p = cell.paragraphs[0]
        r = p.add_run(f"Estimated Fine Collection: Rs. {report_data.get('estimated_fine_collection', 0):.2f}")
        r.bold = True
        r.font.color.rgb = RGBColor.from_string(BLACK)
        r.font.size = Pt(10)

      add_section("Fine Collection Estimate", _fine_content)

      doc.save(file_path)
      return {"success": True, "message": f"Report successfully exported to MS Word '{os.path.basename(file_path)}'!"}
    except Exception as e:
      return {"success": False, "message": f"Word Export Failed: {str(e)}"}
